[project]
org-name = "udeshuk"
version = "0.0.3"
authors = ["UdeshUK"]
license = "Apache-2.0"
repository = "https://github.com/UdeshUK/package-firestore"
keywords = ["ballerina", "Firestore", "endpoint", "connector"]
